[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
pong = { path = "../pong" }
prost = "0.13"
rand = "0.9"
tokio = { version = "1.48.0", features = ["full"] }
wtransport = "0.6.1"

[build-dependencies]
prost-build = "0.13"
